nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Apla_unique.ids Anas_platyrhynchos.ASM874695v1.cds.all.fa >Apla.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Apla_unique.ids Anas_platyrhynchos.ASM874695v1.pep.all.fa  >Apla.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Cpic_unique.ids Chrysemys_picta_bellii.Chrysemys_picta_bellii-3.0.3.cds.all.fa >Cpic.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Cpic_unique.ids Chrysemys_picta_bellii.Chrysemys_picta_bellii-3.0.3.pep.all.fa >Cpic.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Cpor_unique.ids Crocodylus_porosus.CroPor_comp1.cds.all.fa >Cpor.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Cpor_unique.ids Crocodylus_porosus.CroPor_comp1.pep.all.fa >Cpor.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Ggal_unique.ids Gallus_gallus.GRCg6a.cds.all.fa >Ggal.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Ggal_unique.ids Gallus_gallus.GRCg6a.pep.all.fa >Ggal.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Hsap_unique.ids Homo_sapiens.GRCh38.cds.all.fa >Hsap.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Hsap_unique.ids Homo_sapiens.GRCh38.pep.all.fa >Hsap.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Lcha_unique.ids Latimeria_chalumnae.LatCha1.cds.all.fa >Lcha.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Lcha_unique.ids Latimeria_chalumnae.LatCha1.pep.all.fa >Lcha.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Mmus_unique.ids Mus_musculus.GRCm38.cds.all.fa >Mmus.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Mmus_unique.ids Mus_musculus.GRCm38.pep.all.fa >Mmus.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Psin_unique.ids Pelodiscus_sinensis.PelSin_1.0.cds.all.fa >Psin.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Psin_unique.ids Pelodiscus_sinensis.PelSin_1.0.pep.all.fa >Psin.pep.fa &
nohup fishInWinter.pl -bf table -bc 2 -ff fasta --patternmode ../unique_nids/Xtro_unique.ids Xenopus_tropicalis.Xenopus_tropicalis_v9.1.cds.all.fa >Xtro.cds.fa &
nohup fishInWinter.pl -bf table -bc 3 -ff fasta --patternmode ../unique_nids/Xtro_unique.ids Xenopus_tropicalis.Xenopus_tropicalis_v9.1.pep.all.fa >Xtro.pep.fa &
